baseURL = 'https://123duran.github.io/diarioDeLeitura/'
languageCode = 'pt-BR'
title = 'Meu di√°rio de leitura'
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Resenhas"
    url = "/posts/"
    weight = 1
